import Footer from "../components/Footer";
import Header from "../components/Header";
import "../styles/globals.css";

export const metadata = {
  title: "NataNoob's Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <Header />
        <hr className="border-purple-600 mb-10" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
